# -*- coding: utf-8 -*-
"""English_Lemmatizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13m-YngBrYBZor-rnOWRXLw2LgnHBpgbZ
"""

import pandas as pd

def custom_lemmatize(word):
    # Handling common verb forms and irregular verbs
    if word in ['is', 'are', 'was', 'were']:
        return 'be'
    elif word in ['am']:
        return 'be'
    elif word.endswith('ing'):
        return word[:-3]
    elif word.endswith('ed'):
        return word[:-2]
    elif word.endswith('es'):
        return word[:-2]
    elif word.endswith('s'):
        return word[:-1]

    # Handling common adjectives and adverbs
    if word.endswith('er'):
        return word[:-2]
    elif word.endswith('est'):
        return word[:-3]

    # Handling specific common words
    lemmatization_map = {
        'bought': 'buy',
        'went': 'go',
        'gone': 'go',
        'saw': 'see',
        'seen': 'see',
        'ran': 'run',
        'wrote': 'write',
        'written': 'write',
        'knew': 'know',
        'known': 'know',
        'had': 'have',
        'having': 'have',
        'did': 'do',
        'doing': 'do',
        'made': 'make',
        'getting': 'get',
        'got': 'get',
        'puts': 'put',
        'set': 'set',
        'took': 'take',
        'taken': 'take',
    }

    # Checking if the word is in the lemmatization map
    if word in lemmatization_map:
        return lemmatization_map[word]

    return word

# Function to lemmatize a sentence
def lemmatize_sentence(sentence):
    if isinstance(sentence, str):
        words = sentence.split()
        lemmatized_words = [custom_lemmatize(word) for word in words]
        return ' '.join(lemmatized_words)
    else:
        return ''

# Function to apply lemmatization to a column in a CSV file
def lemmatize_column_in_csv(file_path, column_name, output_file):
    df = pd.read_csv(file_path)
    df['Lemmatized_Sentences'] = df[column_name].apply(lemmatize_sentence)

    # Saving the result to a new CSV file
    df.to_csv(output_file, index=False)

    print(f"Lemmatization completed! Results saved to {output_file}")

lemmatize_column_in_csv('/content/Parallel Corpus - Sheet1.csv', 'ENGLISH', 'output_lemmatized.csv')