# -*- coding: utf-8 -*-
"""Kannada_Lemmatizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HAwFFxGaenZVjNL1APSZzaWDZeqH2g6m
"""

import pandas as pd
import re

kannada_suffixes = [
    'ಗಳು', 'ಕೆ', 'ಕ್ಕೆ', 'ಯನ್ನು', 'ನ್ನು', 'ಗಳಿಂದ', 'ದ', 'ವು', 'ಇತ್ತು',
    'ತನ್ಮೂಲಕ', 'ತಾರೆ', 'ಯಾಗ', 'ತಲೆ', 'ಯಲ್ಲಿ', 'ಮಾಡಿದೆ', 'ಮಾಡುತ್ತಿದೆ',
    'ವಿಲ್ಲ', 'ಬರುವ', 'ಗಮನ', 'ನಡುವೆ', 'ಹೊರಡಿದ', 'ಊಟ', 'ಮಾಡುವ', 'ಕೇಳು',
    'ನೀಡುವ', 'ಪಡುವ', 'ಪಡುವ', 'ನಡೆಸುವ', 'ಎನ್ನು', 'ಸೀಮಿತ', 'ಹೋಗುವ',
    'ಬಿಡುವ', 'ಒಯ್ಯುವ', 'ಪರೀಕ್ಷಣೆ', 'ಗೊತ್ತಾಗುವುದು', 'ಸಾಧಿಸಲು', 'ಸಾಧನೆ',
    'ಮಾಡಲು', 'ಹೇಳಲು', 'ಹೇಳುವುದು'
]

# Function to lemmatize a single word based on context
def kannada_lemmatize(word):
    if re.match(r'.*?(ಮಾಡ|ಹೇಳ|ಊಟ|ಬಾಡಿ|ಹೋಗ|ಕಂಡ|ಎನ್ನು|ನಡ|ಸಾಧ|ಓದು).*$', word):
        if word.endswith('ತ್ತದೆ') or word.endswith('ನೀಡುತ್ತದೆ'):
            return re.sub(r'(.+?)(ತ್ತದೆ|ನೀಡುತ್ತದೆ)$', r'\1', word)
        elif word.endswith('ದೆ'):
            return re.sub(r'(.+?)(ದೆ)$', r'\1', word)
        elif word.endswith('ನ'):
            return re.sub(r'(.+?)(ನ)$', r'\1', word)

    if word.endswith('ಗಳು'):
        return re.sub(r'(.+?)(ಗಳು)$', r'\1', word)

    return word

# Function to lemmatize a sentence
def lemmatize_sentence(sentence):
    words = sentence.split()
    lemmatized_words = [kannada_lemmatize(word) for word in words]
    return ' '.join(lemmatized_words)

# Function to apply lemmatization to a column in a CSV file
def lemmatize_column_in_csv(file_path, column_name, output_file):
    df = pd.read_csv('/content/Parallel Corpus - Sheet1.csv')
    df['Lemmatized_Sentences'] = df[column_name].apply(lemmatize_sentence)

    # Saving the result to a new CSV file
    df.to_csv(output_file, index=False)

    print(f"Lemmatization completed! Results saved to {output_file}")

lemmatize_column_in_csv('/content/Parallel Corpus - Sheet1.csv', 'KANNADA', 'output_lemmatized.csv')