# -*- coding: utf-8 -*-
"""Kannada_stemming.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13_mKZNfTIGkkbmGabGfvR0oN4Hnk9b0y
"""

import pandas as pd

# List of common Kannada suffixes for nouns and verbs
kannada_suffixes = sorted([
    'ಗಳು', 'ಕೆ', 'ಕ್ಕೆ', 'ಯನ್ನು', 'ನ್ನು', 'ಗಳನ್ನು', 'ದಿಂದ', 'ದ', 'ವು', 'ಇತ್ತು',
    'ತ್ತು', 'ಡಿದರು', 'ಡಿದ್ದ', 'ಅನು', 'ನ', 'ತೆ', 'ಯ', 'ವ', 'ಕ್ಕೆ', 'ಹಾಗೂ',
    'ವಾಗಿ', 'ತಾನೆ', 'ವುದು', 'ತಿದೆ', 'ಬೇಕಿದೆ', 'ವಳು', 'ಇದರಿಂದ', 'ವನು', 'ವಳು',
    'ನಿಂದ', 'ದರೆ', 'ವರೆಗೆ', 'ಅಲ್ಲಿ', 'ಇಲ್ಲ', 'ತಿದೆ', 'ಅದಕ್ಕೆ', 'ಗಳ', 'ಹೇಗೆ',
    'ಇರುತ್ತದೆ', 'ವಿದ್ದ', 'ವುದು', 'ಕ್ಕಿಂತ', 'ಅಷ್ಟೇ', 'ಗೂ', 'ಅಷ್ಟು', 'ಇದೇ',
    'ಇಲ್ಲದೇ', 'ಇದಕ್ಕೆ', 'ನಲ್ಲಿ', 'ಮೇಲೆ', 'ಕೆಲಸ', 'ಇರುತ್ತದೆ', 'ಅಷ್ಟರಲ್ಲೂ',
    'ವಾದರೂ', 'ಗಿಂತ', 'ಇಲ್ಲದ', 'ದಷ್ಟು', 'ಮಾತ್ರ', 'ಸುತ್ತ', 'ಅವರ', 'ಬಗ್ಗೆ', 'ಇತರೆ',
    'ಮೇಲೆ', 'ಮಾಡಿದೆ', 'ದೊಡ್ಡ', 'ಹೆಚ್ಚಾಗಿ', 'ಅದರಿಂದ', 'ಮಾಡುತ್ತದೆ', 'ಕೇಳಿದ', 'ಎಷ್ಟು'
], key=len, reverse=True)

# Function to stem a single word
def kannada_stem(word):
    word = word.strip()
    for suffix in kannada_suffixes:
        if word.endswith(suffix):
            word = word[:-len(suffix)]
            return word

    return word

# Function to apply stemming to a full sentence/phrase
def stem_sentence(sentence):
    words = sentence.split()
    stemmed_words = [kannada_stem(word) for word in words]
    return ' '.join(stemmed_words)

# Function to apply stemming to each row in a column from a CSV file
def stem_words_in_csv(file_path, column_name, output_file):
    df = pd.read_csv(file_path)
    df[column_name] = df[column_name].astype(str)
    df['Stemmed_Words'] = df[column_name].apply(lambda x: stem_sentence(x))

    # Saving the result to a new CSV file
    df.to_csv(output_file, index=False)

    print(f"Stemming completed! Results saved to {output_file}")

stem_words_in_csv('/content/dataset_kag.csv', 'Kannada', 'output_stemmed.csv')